2025-08-11 19:33:11,110 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2025-08-11 19:33:28,493 [WARNING] django.request: Unauthorized: /api/courses/courses/
2025-08-11 19:33:28,497 [WARNING] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 401 58
2025-08-11 19:33:28,576 [WARNING] django.request: Unauthorized: /api/courses/courses/
2025-08-11 19:33:28,578 [WARNING] django.server: "GET /api/courses/courses/ HTTP/1.1" 401 58
2025-08-11 19:33:28,797 [WARNING] django.request: Unauthorized: /api/users/stats/
2025-08-11 19:33:28,803 [WARNING] django.request: Unauthorized: /api/users/user-activities/
2025-08-11 19:33:28,805 [WARNING] django.request: Unauthorized: /api/users/users/
2025-08-11 19:33:28,811 [WARNING] django.request: Unauthorized: /api/messaging/messages/unread_count/
2025-08-11 19:33:28,812 [WARNING] django.server: "GET /api/users/stats/ HTTP/1.1" 401 58
2025-08-11 19:33:28,852 [WARNING] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 401 58
2025-08-11 19:33:28,853 [WARNING] django.server: "GET /api/messaging/messages/unread_count/ HTTP/1.1" 401 58
2025-08-11 19:33:28,862 [WARNING] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 401 58
2025-08-11 19:33:32,874 [WARNING] django.request: Unauthorized: /api/schedule/schedules/upcoming/
2025-08-11 19:33:32,932 [WARNING] django.server: "GET /api/schedule/schedules/upcoming/ HTTP/1.1" 401 58
2025-08-11 19:33:33,117 [INFO] django.server: "GET /api/payments/site-currency HTTP/1.1" 301 0
2025-08-11 19:33:33,315 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,325 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,331 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,334 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,342 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,353 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,386 [INFO] django.server: "OPTIONS /api/token/refresh/ HTTP/1.1" 200 0
2025-08-11 19:33:33,405 [WARNING] django.request: Unauthorized: /adverts/api/adverts/
2025-08-11 19:33:33,408 [WARNING] django.request: Unauthorized: /api/messaging/messages/stats/
2025-08-11 19:33:33,415 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55204)
2025-08-11 19:33:33,418 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55206)
2025-08-11 19:33:33,477 [WARNING] django.request: Unauthorized: /api/groups/groups/
2025-08-11 19:33:33,544 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55197)
2025-08-11 19:33:33,604 [WARNING] django.request: Not Found: /api/courses/certificates/course/undefined/template/
2025-08-11 19:33:33,606 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55199)
2025-08-11 19:33:36,501 [WARNING] django.request: Unauthorized: /api/schedule/schedules/stats/
2025-08-11 19:33:36,542 [WARNING] django.request: Not Found: /api/courses/faqs/stats/
2025-08-11 19:33:36,544 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55200)
2025-08-11 19:33:36,546 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55220)
2025-08-11 19:33:36,775 [WARNING] django.request: Unauthorized: /api/users/users/
2025-08-11 19:33:36,777 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55227)
2025-08-11 19:33:36,784 [WARNING] django.request: Unauthorized: /api/users/users/
2025-08-11 19:33:36,785 [WARNING] django.request: Unauthorized: /api/courses/courses/
2025-08-11 19:33:36,786 [WARNING] django.request: Unauthorized: /api/courses/courses/
2025-08-11 19:33:36,789 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55224)
2025-08-11 19:33:36,789 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55226)
2025-08-11 19:33:36,790 [INFO] django.server: - Broken pipe from ('127.0.0.1', 55225)
2025-08-11 19:34:03,195 [INFO] django.server: "POST /api/token/ HTTP/1.1" 200 1117
2025-08-11 19:34:08,203 [INFO] django.server: "GET /api/token/validate/ HTTP/1.1" 200 514
2025-08-11 19:34:08,847 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-08-11 19:34:08,865 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-08-11 19:34:08,868 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:34:09,391 [INFO] users: [proliance] Retrieved 6 user activity records
2025-08-11 19:34:09,400 [INFO] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 200 1537
2025-08-11 19:34:11,235 [ERROR] django.request: Internal Server Error: /api/users/stats/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\users\views.py", line 526, in stats
    'new_signups': CustomUser.objects.filter(signup_date__gte=seven_days_ago).count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'signup_date' into field. Choices are: activities, activitylog, assignment, assignmentsubmission, badges, bio, course_ratings, created_adverts, created_categories, created_courses, created_learning_paths, created_schedules, date_joined, email, emailaddress, enrollment, facebook_link, failedlogin, first_name, group_received_messages, groupmembership, groups, id, instructor_profile, is_active, is_deleted, is_locked, is_staff, is_superuser, last_login, last_name, lesson_progress, linkedin_link, logentry, login_attempts, outstandingtoken, password, passwordresettoken, phone, points, profile_picture, received_messages, role, schedule_participations, sent_messages, socialaccount, status, tenant, tenant_id, title, twitter_link, user_permissions, userprofile
2025-08-11 19:34:11,252 [ERROR] django.server: "GET /api/users/stats/ HTTP/1.1" 500 165660
2025-08-11 19:34:12,225 [INFO] django.server: "GET /api/payments/site-currency HTTP/1.1" 301 0
2025-08-11 19:34:12,821 [INFO] django.server: "GET /api/messaging/messages/unread_count/ HTTP/1.1" 200 11
2025-08-11 19:34:12,831 [WARNING] django.request: Not Found: /api/courses/certificates/course/undefined/template/
2025-08-11 19:34:12,836 [WARNING] django.server: "GET /api/courses/certificates/course/undefined/template/ HTTP/1.1" 404 39941
2025-08-11 19:34:13,490 [ERROR] django.request: Internal Server Error: /api/schedule/schedules/upcoming/
2025-08-11 19:34:13,491 [ERROR] django.server: "GET /api/schedule/schedules/upcoming/ HTTP/1.1" 500 46
2025-08-11 19:34:16,207 [WARNING] django.request: Not Found: /api/courses/faqs/stats/
2025-08-11 19:34:16,209 [WARNING] django.server: "GET /api/courses/faqs/stats/ HTTP/1.1" 404 39857
2025-08-11 19:34:17,448 [ERROR] django.request: Internal Server Error: /api/schedule/schedules/stats/
2025-08-11 19:34:17,450 [ERROR] django.server: "GET /api/schedule/schedules/stats/ HTTP/1.1" 500 42
2025-08-11 19:34:18,371 [INFO] django.server: "GET /api/messaging/messages/stats/ HTTP/1.1" 200 31
2025-08-11 19:34:19,703 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:34:21,426 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-08-11 19:34:21,764 [ERROR] django.request: Internal Server Error: /adverts/api/adverts/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "advert_advert" does not exist
LINE 1: ..."."created_at", "advert_advert"."updated_at" FROM "advert_ad...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "advert_advert" does not exist
LINE 1: ..."."created_at", "advert_advert"."updated_at" FROM "advert_ad...
                                                             ^

2025-08-11 19:34:21,776 [ERROR] django.server: "GET /adverts/api/adverts/ HTTP/1.1" 500 186798
2025-08-11 19:34:24,098 [INFO] django.server: "GET /api/groups/groups/?limit=10 HTTP/1.1" 200 648
2025-08-11 19:34:24,099 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-08-11 19:34:25,249 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:34:25,394 [ERROR] django.request: Internal Server Error: /api/users/stats/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\users\views.py", line 526, in stats
    'new_signups': CustomUser.objects.filter(signup_date__gte=seven_days_ago).count(),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ~~~~~~~~~~~~~~~~~^
        child,
        ^^^^^^
    ...<7 lines>...
        update_join_types=update_join_types,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1526, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1333, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\query.py", line 1805, in names_to_path
    raise FieldError(
    ...<2 lines>...
    )
django.core.exceptions.FieldError: Cannot resolve keyword 'signup_date' into field. Choices are: activities, activitylog, assignment, assignmentsubmission, badges, bio, course_ratings, created_adverts, created_categories, created_courses, created_learning_paths, created_schedules, date_joined, email, emailaddress, enrollment, facebook_link, failedlogin, first_name, group_received_messages, groupmembership, groups, id, instructor_profile, is_active, is_deleted, is_locked, is_staff, is_superuser, last_login, last_name, lesson_progress, linkedin_link, logentry, login_attempts, outstandingtoken, password, passwordresettoken, phone, points, profile_picture, received_messages, role, schedule_participations, sent_messages, socialaccount, status, tenant, tenant_id, title, twitter_link, user_permissions, userprofile
2025-08-11 19:34:25,404 [ERROR] django.server: "GET /api/users/stats/ HTTP/1.1" 500 165671
2025-08-11 19:34:26,869 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-08-11 19:34:27,494 [INFO] users: [proliance] Retrieved 6 user activity records
2025-08-11 19:34:27,503 [INFO] django.server: "GET /api/users/user-activities/?limit=10 HTTP/1.1" 200 1537
2025-08-11 19:34:28,549 [INFO] django.server: "GET /api/messaging/messages/unread_count/ HTTP/1.1" 200 11
2025-08-11 19:34:28,562 [INFO] django.server: "GET /api/payments/site-currency HTTP/1.1" 301 0
2025-08-11 19:34:28,651 [ERROR] django.request: Internal Server Error: /api/schedule/schedules/upcoming/
2025-08-11 19:34:28,652 [ERROR] django.server: "GET /api/schedule/schedules/upcoming/ HTTP/1.1" 500 46
2025-08-11 19:34:30,268 [WARNING] django.request: Not Found: /api/courses/certificates/course/undefined/template/
2025-08-11 19:34:30,270 [WARNING] django.server: "GET /api/courses/certificates/course/undefined/template/ HTTP/1.1" 404 39941
2025-08-11 19:34:32,315 [WARNING] django.request: Not Found: /api/courses/faqs/stats/
2025-08-11 19:34:32,335 [WARNING] django.server: "GET /api/courses/faqs/stats/ HTTP/1.1" 404 39857
2025-08-11 19:34:33,311 [ERROR] django.request: Internal Server Error: /api/schedule/schedules/stats/
2025-08-11 19:34:33,312 [ERROR] django.server: "GET /api/schedule/schedules/stats/ HTTP/1.1" 500 42
2025-08-11 19:34:34,620 [INFO] django.server: "GET /api/messaging/messages/stats/ HTTP/1.1" 200 31
2025-08-11 19:34:35,760 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:34:36,096 [INFO] django.server: "GET /api/groups/groups/?limit=10 HTTP/1.1" 200 648
2025-08-11 19:34:37,599 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=10 HTTP/1.1" 200 78
2025-08-11 19:34:38,694 [ERROR] django.request: Internal Server Error: /adverts/api/adverts/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "advert_advert" does not exist
LINE 1: ..."."created_at", "advert_advert"."updated_at" FROM "advert_ad...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\serializers.py", line 797, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\serializers.py", line 251, in data
    self._data = self.to_representation(self.instance)
                 ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\serializers.py", line 716, in to_representation
    self.child.to_representation(item) for item in iterable
                                                   ^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "advert_advert" does not exist
LINE 1: ..."."created_at", "advert_advert"."updated_at" FROM "advert_ad...
                                                             ^

2025-08-11 19:34:38,705 [ERROR] django.server: "GET /adverts/api/adverts/ HTTP/1.1" 500 186798
2025-08-11 19:34:42,573 [ERROR] django.request: Internal Server Error: /api/payments/site-currency/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "payments_siteconfig" does not exist
LINE 1: ...."title", "payments_siteconfig"."updated_at" FROM "payments_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\payments\views.py", line 94, in list
    config = SiteConfig.objects.first()
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1104, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "payments_siteconfig" does not exist
LINE 1: ...."title", "payments_siteconfig"."updated_at" FROM "payments_...
                                                             ^

2025-08-11 19:34:42,589 [ERROR] django.server: "GET /api/payments/site-currency/ HTTP/1.1" 500 177522
2025-08-11 19:34:43,301 [ERROR] django.request: Internal Server Error: /api/payments/site-currency/
Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "payments_siteconfig" does not exist
LINE 1: ...."title", "payments_siteconfig"."updated_at" FROM "payments_...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 515, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 486, in raise_uncaught_exception
    raise exc
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\rest_framework\views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\payments\views.py", line 94, in list
    config = SiteConfig.objects.first()
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1104, in first
    for obj in queryset[:1]:
               ~~~~~~~~^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 384, in __iter__
    self._fetch_all()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
        chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size
    )
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.ProgrammingError: relation "payments_siteconfig" does not exist
LINE 1: ...."title", "payments_siteconfig"."updated_at" FROM "payments_...
                                                             ^

2025-08-11 19:34:43,313 [ERROR] django.server: "GET /api/payments/site-currency/ HTTP/1.1" 500 177522
2025-08-11 19:34:59,630 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-08-11 19:34:59,631 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-08-11 19:34:59,657 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-08-11 19:34:59,658 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 52
2025-08-11 19:35:00,194 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-08-11 19:35:00,206 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-08-11 19:35:03,893 [INFO] django.server: "GET /api/courses/categories/ HTTP/1.1" 200 52
2025-08-11 19:35:03,962 [INFO] django.server: "GET /api/courses/enrollments/all/ HTTP/1.1" 200 52
2025-08-11 19:35:04,007 [INFO] django.server: "GET /api/courses/courses/most_popular/ HTTP/1.1" 200 45
2025-08-11 19:35:04,100 [INFO] django.server: "GET /api/courses/courses/least_popular/ HTTP/1.1" 200 45
2025-08-11 19:35:05,249 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 78
2025-08-11 19:35:05,250 [INFO] django.server: "GET /api/courses/courses/?page=1&page_size=1000 HTTP/1.1" 200 78
2025-08-11 19:35:26,172 [INFO] django.server: "GET /api/users/users/?page_size=1000 HTTP/1.1" 200 776
2025-08-11 19:35:26,173 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:35:26,174 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:35:30,288 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:35:30,313 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:35:31,072 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-08-11 19:35:31,655 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-08-11 19:35:34,864 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:35:36,036 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:35:36,279 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-08-11 19:35:39,358 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:35:39,971 [INFO] django.server: "GET /api/users/users/?page_size=1000 HTTP/1.1" 200 776
2025-08-11 19:35:40,283 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-08-11 19:35:40,859 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:35:41,120 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:35:41,378 [INFO] django.server: "GET /api/courses/courses/ HTTP/1.1" 200 78
2025-08-11 19:35:45,062 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:35:45,621 [INFO] django.server: "GET /api/users/users/?page=1&page_size=10 HTTP/1.1" 200 775
2025-08-11 19:35:48,241 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:35:49,863 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 648
2025-08-11 19:38:04,140 [INFO] users.serializers: User created successfully: student1@prolianceltd.com in tenant proliance
2025-08-11 19:38:08,135 [INFO] django.server: "POST /api/users/register/ HTTP/1.1" 201 393
2025-08-11 19:38:17,769 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:38:19,012 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 1226
2025-08-11 19:38:49,975 [INFO] users.serializers: User created successfully: student2@prolianceltd.com in tenant proliance
2025-08-11 19:38:54,585 [INFO] django.server: "POST /api/users/register/ HTTP/1.1" 201 390
2025-08-11 19:39:04,464 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:39:05,707 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 1802
2025-08-11 19:39:33,070 [INFO] users.serializers: User created successfully: student3@prolianceltd.com in tenant proliance
2025-08-11 19:39:38,556 [INFO] django.server: "POST /api/users/register/ HTTP/1.1" 201 388
2025-08-11 19:39:49,622 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:39:50,341 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 2376
2025-08-11 19:40:25,862 [INFO] users.serializers: User created successfully: student4@prolianceltd.com in tenant proliance
2025-08-11 19:40:30,234 [INFO] django.server: "POST /api/users/register/ HTTP/1.1" 201 388
2025-08-11 19:40:40,108 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:40:41,461 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 2950
2025-08-11 19:41:16,242 [INFO] users.serializers: User created successfully: instructor1@prolianceltd.com in tenant proliance
2025-08-11 19:41:20,400 [INFO] django.server: "POST /api/users/register/ HTTP/1.1" 201 390
2025-08-11 19:41:30,509 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:41:31,826 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 3526
2025-08-11 19:41:33,875 [INFO] django.server: "OPTIONS /api/users/user-activities/?user_id=7 HTTP/1.1" 200 0
2025-08-11 19:41:33,878 [INFO] django.server: "OPTIONS /api/courses/enrollments/user/7/ HTTP/1.1" 200 0
2025-08-11 19:41:33,891 [INFO] django.server: "OPTIONS /api/messaging/messages/?recipient_id=7 HTTP/1.1" 200 0
2025-08-11 19:41:38,789 [INFO] django.server: "GET /api/messaging/messages/?recipient_id=7 HTTP/1.1" 200 2
2025-08-11 19:41:40,103 [INFO] users: [proliance] Retrieved 4 user activity records
2025-08-11 19:41:40,108 [INFO] django.server: "GET /api/users/user-activities/?user_id=7 HTTP/1.1" 200 1001
2025-08-11 19:41:40,404 [INFO] django.server: "GET /api/courses/enrollments/user/7/ HTTP/1.1" 200 2
2025-08-11 19:41:42,240 [INFO] django.server: "OPTIONS /api/users/users/7/ HTTP/1.1" 200 0
2025-08-11 19:41:52,390 [INFO] users: [proliance] User soft-deleted: instructor1@prolianceltd.com
2025-08-11 19:41:52,684 [INFO] django.server: "DELETE /api/users/users/7/ HTTP/1.1" 204 38
2025-08-11 19:41:53,313 [WARNING] django.request: Not Found: /api/users/users/7/
2025-08-11 19:41:53,316 [WARNING] django.server: "DELETE /api/users/users/7/ HTTP/1.1" 404 51
2025-08-11 19:41:57,817 [INFO] users: [proliance] User soft-deleted: instructor1@prolianceltd.com
2025-08-11 19:41:58,229 [INFO] django.server: "DELETE /api/users/users/7/ HTTP/1.1" 204 38
2025-08-11 19:42:02,847 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:42:04,141 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 3527
2025-08-11 19:42:08,676 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:42:10,430 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 3527
2025-08-11 19:42:37,185 [INFO] users.serializers: User created successfully: instructor2@prolianceltd.com in tenant proliance
2025-08-11 19:42:41,237 [INFO] django.server: "POST /api/users/register/ HTTP/1.1" 201 393
2025-08-11 19:42:51,843 [INFO] django.server: "GET /api/groups/roles/ HTTP/1.1" 200 378
2025-08-11 19:42:53,234 [INFO] django.server: "GET /api/groups/groups/ HTTP/1.1" 200 4164
2025-08-11 19:45:38,753 [INFO] django.utils.autoreload: C:\Users\CPT-003\Desktop\Proliance Source Codes\Backend\complete_lms_api\lumina_care\settings.py changed, reloading.
2025-08-11 19:45:43,635 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
